default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: nazarhlynskyi
  password: 

development:
  <<: *default
  database: dev_jetruby

test:
  <<: *default
  database: test_jetruby